name: Run jupyter notebook tests

on: push

jobs:
  run_test:
    name: Build docker image
    runs-on: self-hosted
    steps:
      - name: build_test
        shell: bash -l {0}
        run: |
            export MY_TEST_VAR="hello"
            echo $MY_TEST_VAR
            cd ~/chipwhisperer/jupyter/tests/docker
            docker build . -t cw-testing-server