name: Run jupyter notebook tests

on: push

jobs:
  run_test:
    name: Build docker image
    runs-on: self-hosted
    steps:
      - name: build_test
        shell: bash -l {0}
        run: >-
          bash -c '
          echo $USER 
          pwd 
          cat ~/.bashrc 
          chmod +x ~/.bashrc
          source ~/.bashrc 
          echo $MY_TEST_VAR 
          build_test '