name: Run jupyter notebook tests

on: push

jobs:
  run_test:
    defaults:
      run:
        shell: bash
    name: Build docker image
    runs-on: self-hosted
    steps:
       - run: |
          echo $USER 
          pwd 
          cat ~/.bashrc 
          source ~/.bashrc 
          echo $MY_TEST_VAR 
          build_test