name: Run jupyter notebook tests

on: push

jobs:
  run_test:
    name: Build docker image
    runs-on: self-hosted
    steps:
       - run: >- 
          echo $USER &&
          pwd &&
          cat ~/.bashrc &&
          source ~/.bashrc &&
          build_test