name: Run jupyter notebook tests

on: push

jobs:
  run_test:
    name: Build docker image
    runs-on: self-hosted
    steps:
      - name: build_test
        shell: bash -l {0}
        run: |
            if [ -n "$(docker ps -q)" ]; then
              exit 1
            fi
            echo "Running build"
            cd ~/chipwhisperer/jupyter/tests/docker
            docker build . -t cw-testing-server

