name: Update private repo

on: push

- name: Invoke workflow in another repo with inputs
  uses: benc-uk/workflow-dispatch@v1
  with:
    workflow: Run Tests
    repo: newaetech/ChipWhisperer-Private-Tests
    token: ${{ secrets.PRIVATE_TEST_PUSH }}